name: Deploy Vite App to GitHub Pages

on:
  push:
    branches:
      - main  # Change if your main branch has a different name

  workflow_dispatch:  # Allows manual deployment from the Actions tab

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18  # Use the Node.js version required by your project

      - name: Install dependencies
        run: npm install

      - name: Build the project
        run: npm run build

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v2
        with:
          path: dist  # Vite builds output to the "dist" folder

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
